table dim_landpads
	lineageTag: 6644fb29-3df0-4ecf-be6b-304d705d1f04

	column details
		dataType: string
		lineageTag: bbd32eb4-7242-402f-97ec-f1a28a636c27
		summarizeBy: none
		sourceColumn: details

		annotation SummarizationSetBy = Automatic

	column full_name
		dataType: string
		lineageTag: 1b7e52e5-319d-48b4-b813-bb8b789c0e00
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

	column landpad_id
		dataType: int64
		formatString: 0
		lineageTag: d5a74467-5c13-4363-9c1f-954ee2b45038
		summarizeBy: none
		sourceColumn: landpad_id

		annotation SummarizationSetBy = Automatic

	column landing_attempts
		dataType: int64
		formatString: 0
		lineageTag: ccfc1dad-e015-4932-9f45-8d2a5cc7ebb3
		summarizeBy: none
		sourceColumn: landing_attempts

		annotation SummarizationSetBy = Automatic

	column landing_successes
		dataType: int64
		formatString: 0
		lineageTag: 0eba0d2b-47e6-437a-a912-525637dd4fde
		summarizeBy: none
		sourceColumn: landing_successes

		annotation SummarizationSetBy = Automatic

	column locality
		dataType: string
		lineageTag: af974b60-9e48-4ed2-afe8-9247a5e03744
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column landpad_name
		dataType: string
		lineageTag: 1c9cd438-7a40-48bb-874e-a944d82bee1e
		summarizeBy: none
		sourceColumn: landpad_name

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 9b680427-3814-44e9-b26a-5965af96c25a
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: bdae07b0-8f00-4e7a-86ff-7c8a478b3e94
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column landpad_type
		dataType: string
		lineageTag: dd49d346-e025-446f-b600-fa4a718c08d4
		summarizeBy: none
		sourceColumn: landpad_type

		annotation SummarizationSetBy = Automatic

	column landtype_type_text = IF(dim_landpads[landpad_type] = "RTLS", "Land", "Ocean")
		lineageTag: f53105c9-6794-4f2d-8f83-a1ad81a5bb72
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 7cd35056-757b-4683-b818-30be4036e252
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: f64960cd-b8f9-4716-a5ab-f79e2cde7da5
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dim_landpads = m
		mode: import
		source =
				let
				    Source = Sql.Databases("group2spacex.sql.azuresynapse.net", [CreateNavigationProperties=false]),
				    group2spacexDP = Source{[Name="group2spacexDP"]}[Data],
				    dbo_dim_landpads = group2spacexDP{[Schema="dbo",Item="dim_landpads"]}[Data],
				    #"Sorted Rows" = Table.Sort(dbo_dim_landpads,{{"landpad_type", Order.Ascending}}),
				    #"Added Custom" = Table.AddColumn(#"Sorted Rows", "Custom", each if [locality] = "Port Canaveral" then "28,4104" else [latitude]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Custom", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"latitude"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Custom", "latitude"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "Custom", each if [locality] = "Port Canaveral" then "-80,6188" else [longitude]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Custom", type number}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"longitude"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Custom", "longitude"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

