table dim_cores
	lineageTag: 5e0a781b-73f0-4041-8a2f-04f26acb5c76

	measure KPI_Color_rtls = ```
			
			IF(
			    SUM(dim_cores[rtls_landings]) < SUM(dim_cores[rtls_attempts]),
			    "#B9000D",  
			    "#0EB194"    
			)
			```
		lineageTag: b5d1da48-65f8-4f15-9b3c-883d356322c2

	measure KPI_Color_asds = ```
			
			IF(
			    SUM(dim_cores[asds_landings]) < SUM(dim_cores[asds_attempts]),
			    "#B9000D",  
			    "#0EB194"    
			)
			```
		lineageTag: 60cc1ef5-8931-4dc6-90e2-b137279d8f26

	column asds_attempts
		dataType: int64
		formatString: 0
		lineageTag: bc2963bf-3b35-4db4-8c5c-44a1b41175e0
		summarizeBy: none
		sourceColumn: asds_attempts

		annotation SummarizationSetBy = Automatic

	column asds_landings
		dataType: int64
		formatString: 0
		lineageTag: 69c64fe6-427d-48bb-8486-c74d925bef04
		summarizeBy: none
		sourceColumn: asds_landings

		annotation SummarizationSetBy = Automatic

	column core_block
		dataType: int64
		formatString: 0
		lineageTag: 375dbd99-ef35-4f91-8e01-c066739421e7
		summarizeBy: none
		sourceColumn: core_block

		annotation SummarizationSetBy = Automatic

	column core_id
		dataType: int64
		formatString: 0
		lineageTag: 27cdfec6-76e4-4ece-81a2-47c677827e3e
		summarizeBy: none
		sourceColumn: core_id

		annotation SummarizationSetBy = Automatic

	column last_update
		dataType: string
		lineageTag: a97e7cb0-554b-4d75-bdc4-ee800ff8bc44
		summarizeBy: none
		sourceColumn: last_update

		annotation SummarizationSetBy = Automatic

	column reuse_count
		dataType: int64
		formatString: 0
		lineageTag: 08c66c5a-a740-4a8a-a3fb-ad71f7baa55c
		summarizeBy: none
		sourceColumn: reuse_count

		annotation SummarizationSetBy = Automatic

	column rtls_attempts
		dataType: int64
		formatString: 0
		lineageTag: 33ad1049-69f4-459a-b462-b6171f940f92
		summarizeBy: none
		sourceColumn: rtls_attempts

		annotation SummarizationSetBy = Automatic

	column rtls_landings
		dataType: int64
		formatString: 0
		lineageTag: 144d1208-dfc7-466a-b73e-a1adc2b34aee
		summarizeBy: none
		sourceColumn: rtls_landings

		annotation SummarizationSetBy = Automatic

	column core_status
		dataType: string
		lineageTag: 717d7349-c04a-4d02-ad30-939ec43989ce
		summarizeBy: none
		sourceColumn: core_status

		annotation SummarizationSetBy = Automatic

	column core_reused = IF(dim_cores[reuse_count] > 0, "Reused", "Disposed")
		lineageTag: 0f0fe6d6-1870-46b0-bbd1-5c6145ff5760
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dim_cores = m
		mode: import
		source =
				let
				    Source = Sql.Databases("group2spacex.sql.azuresynapse.net", [CreateNavigationProperties=false]),
				    group2spacexDP = Source{[Name="group2spacexDP"]}[Data],
				    dbo_dim_cores = group2spacexDP{[Schema="dbo",Item="dim_cores"]}[Data]
				in
				    dbo_dim_cores

	annotation PBI_ResultType = Table

